// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTw9tydZXYRJ99pzzaQqgKg98p00zVR4',
    appId: '1:760164097376:web:4bf1ab21a05a6fde329205',
    messagingSenderId: '760164097376',
    projectId: 'srinivas-temple-website',
    authDomain: 'srinivas-temple-website.firebaseapp.com',
    storageBucket: 'srinivas-temple-website.firebasestorage.app',
    measurementId: 'G-S8PGG5F3RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22P82btKJPWYtCfDLjlL1kc_QziEfEjA',
    appId: '1:760164097376:android:34117e10a7b002dc329205',
    messagingSenderId: '760164097376',
    projectId: 'srinivas-temple-website',
    storageBucket: 'srinivas-temple-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDks0Lr0MkpVcBRaYqyyX7wCsYrV1JAik',
    appId: '1:760164097376:ios:a49336f33dbf5a59329205',
    messagingSenderId: '760164097376',
    projectId: 'srinivas-temple-website',
    storageBucket: 'srinivas-temple-website.firebasestorage.app',
    iosBundleId: 'com.example.staffClientSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDks0Lr0MkpVcBRaYqyyX7wCsYrV1JAik',
    appId: '1:760164097376:ios:a49336f33dbf5a59329205',
    messagingSenderId: '760164097376',
    projectId: 'srinivas-temple-website',
    storageBucket: 'srinivas-temple-website.firebasestorage.app',
    iosBundleId: 'com.example.staffClientSide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnTw9tydZXYRJ99pzzaQqgKg98p00zVR4',
    appId: '1:760164097376:web:918d7d160b77548d329205',
    messagingSenderId: '760164097376',
    projectId: 'srinivas-temple-website',
    authDomain: 'srinivas-temple-website.firebaseapp.com',
    storageBucket: 'srinivas-temple-website.firebasestorage.app',
    measurementId: 'G-E3KHEHFLBF',
  );

}