// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnsCkm0JRWW1GJcTcCppTqO1Fa8Yhhds',
    appId: '1:590052843427:web:74440048d6afc415a34416',
    messagingSenderId: '590052843427',
    projectId: 'manomay-19162',
    authDomain: 'manomay-19162.firebaseapp.com',
    storageBucket: 'manomay-19162.appspot.com',
    measurementId: 'G-ZYE34CX1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLD1RSbXn3iG0HhlITDwcY3PsgAQlnnS4',
    appId: '1:590052843427:android:d857877017377bada34416',
    messagingSenderId: '590052843427',
    projectId: 'manomay-19162',
    storageBucket: 'manomay-19162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvO_iDDYNbzqb7OsNEIBXxJvvoYdG8vNo',
    appId: '1:590052843427:ios:fa5a3e61951d8f58a34416',
    messagingSenderId: '590052843427',
    projectId: 'manomay-19162',
    storageBucket: 'manomay-19162.appspot.com',
    iosBundleId: 'com.example.staffClientSide',
  );
}
